name: Update

on:
  schedule: 
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Run a multi-line script
        run: |
          wget https://www.post.japanpost.jp/zipcode/dl/kogaki/zip/ken_all.zip -P $GITHUB_WORKSPACE
          wget https://www.post.japanpost.jp/zipcode/dl/jigyosyo/zip/jigyosyo.zip -P $GITHUB_WORKSPACE

      - uses: stefanzweifel/git-auto-commit-action@v4
