name: Update

on:
  schedule: 
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Run a multi-line script
        run: |
          rm -f "$GITHUB_WORKSPACE/ken_all.zip"
          rm -f "$GITHUB_WORKSPACE/jigyosyo.zip"
          wget -P "$GITHUB_WORKSPACE" https://www.post.japanpost.jp/zipcode/dl/kogaki/zip/ken_all.zip
          wget -P "$GITHUB_WORKSPACE" https://www.post.japanpost.jp/zipcode/dl/jigyosyo/zip/jigyosyo.zip

      - uses: stefanzweifel/git-auto-commit-action@v4
